# Site settings
title: FricolaB - People Oriented Open Source Software
email: info@fricolab.com
description: > # this means to ignore newlines until "baseurl:"
  Fricolab is a multidisciplinary project led by David A. Lareo. We believe in open technology as one of the main tools for promoting social change and helping to build a fairer and more beautiful world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fricolab.github.io/" # the base hostname & protocol for your site
twitter_username: fricolab
github_username:  fricolab

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
